### ISSUE TITLE
[bug] Basic Examples Do Not Work With `cairo1-run`

### ISSUE THREAD

**Issue by neotheprogramist** [neotheprogramist/cairo-vm#1]
# How to Use

1. Clone the repository:
   ```
   git clone git@github.com:neotheprogramist/cairo-vm.git
   ```
2. Navigate to the directory:
   ```
   cd cairo-vm/cairo1-run
   ```
3. Checkout the branch with issues/examples:
   ```
   git checkout issues/examples
   ```
4. Install dependencies:
   ```
   make deps
   ```

## Description
There are issues encountered when running Cairo programs using different methods (`cargo` and `scarb`). The details for each example are provided below along with the specific problems and suggested solutions.

### Example 1
1. **Self-check Command:**
   ```
   cargo run -r -- --layout recursive --print_output --proof_mode --args_file example1/args.txt example1/src/lib.cairo
   ```
2. **Issue:**
   - The `example1/args.txt` file cannot have a trailing newline.
   - If it has a trailing newline, the following error occurs:
     ```
     thread 'main' panicked at cairo1-run/src/main.rs:107:68:
     called `Result::unwrap()` on an `Err` value: FromStrError
     ```
3. **Running with `scarb`:**
   ```
   scarb cairo-run -p example1 "[10]"
   ```
   - Arrays are printed incorrectly (as pointers instead of values).

### Example 2
1. **Command:**
   ```
   cargo run -r -- --layout recursive --print_output --proof_mode --args_file example2/args.txt example2/src/lib.cairo
   ```
2. **Issue in Proof Mode:**
   - Only arrays can be returned in proof mode.
   - Returning a simple `felt252` results in an error:
     ```
     Error: IlegalReturnValue
     ```
3. **Non-proof Mode:**
   ```
   cargo run -r -- --layout recursive --print_output --args_file example2/args.txt example2/src/lib.cairo
   ```
   - Works fine without proof mode.

### Example 3
1. **Command:**
   ```
   cargo run -r -- --layout recursive --print_output --args_file example3/args.txt example3/src/lib.cairo
   ```
2. **Issue with Proof Mode Off:**
   - Passing an array as `n, a_1, a_2, ..., a_n` results in an error:
     ```
     thread 'main' panicked at cairo1-run/src/cairo_run.rs:1045:18:
     Array start_ptr not Relocatable
     ```
3. **Proof Mode:**
   ```
   cargo run -r -- --layout recursive --print_output --proof_mode --args_file example3/args.txt example3/src/lib.cairo
   ```
   - Cannot properly access the array.
4. **Running with `scarb`:**
   ```
   scarb cairo-run -p example3 "[[10]]"
   ```
   - Works properly.

### Suggested Solution
- Change the `args.txt` file format to the one used by `scarb`.

## Tasks to Do
1. **Example 1:**
   - [ ] Ensure `example1/args.txt` does not have a trailing newline.
   - [ ] Investigate and fix the issue with `scarb` printing arrays incorrectly.

2. **Example 2:**
   - [ ] Update the code to handle returning simple `felt252` in proof mode.
   - [ ] Verify and ensure the program works correctly in both proof and non-proof modes.

3. **Example 3:**
   - [ ] Fix the issue of passing arrays in non-proof mode.
   - [ ] Resolve array access issues in proof mode.
   - [ ] Update the `args.txt` file format to match the one used by `scarb`.

**Comment by fmoletta** [comment]
Only allowing arrays as input/output is currently needed in order to make programs provable.
Passing arrays as `n, a_1, a_2, ..., a_n` doesn't work because it is not the correct format, `[a_1 a_2 ... an]` is the correct one.
This is documented in the `cairo1-run` [README](https://github.com/lambdaclass/cairo-vm/blob/main/cairo1-run/README.md).
As for the problem with newlines in the args_file, this will be fixed along with other issues by [PR](https://github.com/lambdaclass/cairo-vm/pull/1782)
